---

- name: Provision a {{ application_name }} server
  hosts: all
  sudo: yes
  sudo_user: "{{ sudo_user }}"
  remote_user: "{{ remote_user }}"
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/private
    - env_vars/base
    - env_vars/dev

  roles:
    - base
    - db-fedora
    - web
    - memcached