---
- name: install and configure all website services 
  hosts: dbservers
  sudo_user: "{{ sudo_user }}"
  remote_user: "{{ remote_user }}"
  vars_files:
    - env_vars/base
    - private/vars.yml
  roles:
    - base
    - db
    - freetds
    - supervisor
    - web
