---

# Check whether repo packages are installed before forcing a network download.

# - name: is the rpmfusion-free repo installed
#   command: rpm -q rpmfusion-free-release
#   register: rpmfusion_free_installed
#   ignore_errors: True
#   changed_when: rpmfusion_free_installed|failed

# - name: is the rpmfusion-nonfree repo installed
#   command: rpm -q rpmfusion-nonfree-release
#   register: rpmfusion_nonfree_installed
#   ignore_errors: True
#   changed_when: rpmfusion_nonfree_installed|failed

- name: is the livna repo installed
  command: rpm -q livna-release
  register: livna_installed
  ignore_errors: True
  changed_when: livna_installed|failed


# Install missing repo packages.

# - name: install rpmfusion-free yum repo
#   yum:
#     name: http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
#     state: present
#   when: rpmfusion_free_installed|failed

# - name: install rpmfusion-nonfree yum repo
#   yum:
#     name: http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
#     state: present
#   when: rpmfusion_nonfree_installed|failed

- name: install livna yum repo required for video editing packages
  yum:
    name: http://rpm.livna.org/livna-release.rpm
    state: present
  when: livna_installed|failed

- name: install video and animation editting packages
  # apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  # with_items:
  #   - build-essential
  #   - htop
  #   - git
  #   - python-dev
  #   - python-pip
  #   - python-pycurl
  #   - supervisor
  yum: name={{ item }} state=installed
  with_items:
    - gstreamer-plugins-bad
    - gstreamer-plugins-bad-free-extras
    - gstreamer-plugins-bad-nonfree
    - gstreamer-plugins-ugly
    - gstreamer-ffmpeg
    - ffmpeg mencoder
    - ffmpeg2theora
    - mplayer
    - libdvdcss
    - ImageMagick
    - gstreamer1-libav
  tags:
    - packages
    - yum

- name: pip install python development and data analysis tools
  pip: name={{ item }} state=latest
  with_items:
    - ipython
    - numpy
    - pandas
    - scipy
    - pycallgraph
    - psutil


