---

#sudo groupadd --system bigdata
- name: create webapp group
  group: name={{ webapps_group }} system=yes state=present

# sudo groupadd --system webapps
- name: create webapps group
  group: name={{ webapps_group }} system=yes state=present

# sudo useradd --system --gid webapps --shell /bin/bash --home /webapps/bigdata bigdata
- name: create webapp user
  user: name={{ gunicorn_user }}
        system=yes state=present
        groups={{ webapps_group }},{{ gunicorn_user }}
        home={{ virtualenv_path }}
        append=yes
#        move_home=yes

- name: add nginx user to the webapp group
  user: name=nginx groups="{{ webapps_group }},nginx" state=present append=yes
