---

- name: install nginx
#  apt: name=nginx update_cache={{ update_apt_cache }} state=installed
  yum: name=nginx state=installed
  tags: packages

- name: stop nginx
  service: name=nginx state=stopped

# - name: Copy the SSL cert and key to the remote server
#   copy: src={{ ssl_src_dir }}/ dest={{ ssl_dest_dir }}

# - name: Decrypt the SSL key
#   command: openssl aes-256-cbc -salt -a -d -in {{ ssl_dest_dir }}/nginx.key
#            -out {{ ssl_dest_dir }}/decrypted.key -k {{ ssl_key_password }}
#            creates={{ ssl_dest_dir }}/decrypted.key

# - name: Rename the decrypted SSL key
#   command: mv {{ ssl_dest_dir }}/decrypted.key {{ ssl_dest_dir }}/nginx.key
#            removes={{ ssl_dest_dir }}/decrypted.key

- name: add required nginx directories
  file: dest="{{ item }}" state=directory
  with_items:
  - "/etc/nginx/sites-available"
  - "/etc/nginx/sites-enabled"
  - "{{ application_log_dir }}"
  - "{{ nginx_static_dir }}" 
  - "{{ nginx_media_dir }}" 

- name: create nginx configuration file
  template: src=nginx_site_config.j2
            dest=/etc/nginx/sites-available/{{ application_name }}
            backup=yes

- name: disable default nginx site
  command: rm /etc/nginx/sites-enabled/default
           removes=/etc/nginx/sites-enabled/default

- name: enable application nginx site
  command: ln -s /etc/nginx/sites-available/{{ application_name }}
           /etc/nginx/sites-enabled/{{ application_name }}
           creates=/etc/nginx/sites-enabled/{{ application_name }}

- name: start nginx
  service: name=nginx state=started enabled=yes