---
- name: create /etc/supervisord.conf
  shell: echo_supervisord_conf > /etc/supervisord.conf; mkdir -p /etc/supervisor/conf.d/
  sudo: yes

- name: Create Supervisor config files for each application?
  template: src=supervisor_config.j2
            backup=yes
            dest=/etc/supervisor/conf.d/{{ application_name }}.conf

- name: stop supervisord
  service: name=supervisord state=stopped enabled=yes

# - name: reread the supervisord config files
#   command: supervisorctl reread

- name: start supervisord
  service: name=supervisord state=started enabled=yes

- name: update supbervisord to add the new app
  command: supervisorctl update

# - name: add programs to process group
#   shell: supervisorctl add {{item.name}}
#   when: supervisor.programs is defined
#   with_items: supervisor.programs

# - name: change supervisord programs states
#   shell: supervisorctl start {{item.name}}
#   when: supervisor.programs is defined
#   with_items: supervisor.programs
