#!/bin/bash
# Restore a database *locally* from /backups/.

DB_PATH=$1

# filename extension expected for pg_dump output scripts (e.g. "dump" or "pg" or "sql" or "pgsql" or "psql")
EXT=".psql"
XZ_EXT=".xz"
# pg_dump format option: plain (sql) or custom (binary)
DUMP_FORMAT="plain"


source restore-database "$DB_PATH" "$EXT" "$XZ_EXT" "$DUMP_FORMAT" 
