---
- name: copy sshd_config 
  copy:
    dest=/etc/ssh/sshd_config
    src=private/files/ssh/sshd_config
    mode=600
  notify:
    - restart sshd
  tags:
    - sshd_config
    - config
    - sshd

# - include: prepare.yml
- include: user_accounts.yml
# - include: ssh.yml
# - include: sudo.yml
# - name: /tmp/ansible/ directory exists with 0777 permission
#   file: path=/tmp/ansible/ owner=root group=root mode=0777 recurse=no state=directory
#   sudo: yes

# - name: /var/log/yum.log file exists with 0777 permission
#   file: path=/var/log/yum.log owner=root group=root mode=0777 recurse=no state=file
#   sudo: yes

- name: install vmware tools
  yum: name={{ item }}  state=installed
  with_items:
    - open-vm-tools
  tags: packages

- name: Ensure OpenSSl and libssl are the latest versions
#  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest    
#  with_items:
#    - openssl
#    - libssl-dev
#    - libssl-doc
  yum: name={{ item }} state=latest
  with_items:
    - openssl
    - openssl-devel
    - openssl-static
    - openssl-perl
  tags: packages

- name: install base packages
  # apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  # with_items:
  #   - build-essential
  #   - htop
  #   - git
  #   - python-dev
  #   - python-pip
  #   - python-pycurl
  #   - supervisor
  yum: name={{ item }} state=installed
  with_items:
    - '"@Development Tools"'
    - git
    - curl
    - wget
    - htop
    - nano
    - tree
    - graphviz  # required by pygraphviz and django db graph
    - graphviz-devel  # required by pygraphviz and django db graph
    - python-devel
    - python-pycurl
    - ipython
    - unixODBC-devel
    - gcc
    - gcc-c++
    - compat-gcc-34-c++

    # required by pyodbc
    # - libxml
    # - libxml++
    - libxml2
    - libxml2-devel
    - libxslt
    - libxslt-devel
    # - libxml++-devel

    # required by numpy and scipy
    - blas-static
    - lapack-static
    - numpy-f2py  
    - gcc-gfortran 
    - numpy
    - scipy

    # these might work OK with pip install, but scipy.org requires them
    - python-matplotlib
    - python-pandas
    - sympy
    - python-nose
  tags:
    - packages
    - yum

- name: install latest (non-yum) pip as well as ansible (on the ansible node vm!)
  # TODO: nested sudoing here seems odd
  shell: curl --silent --insecure --location https://bootstrap.pypa.io/get-pip.py | python; pip install ansible
  sudo: yes
  tags: pip

- name: pip install virtualenv
  pip: name={{ item }} state=latest
  with_items:
    - virtualenv
    - virtualenvwrapper
  # - newrelic
  tags:
    - pip
    - python

- name: pip install supervisor
  pip: name=supervisor state=latest
  tags:
    - pip
    - python

- name: pip install setproctitle
  pip: name=supervisor state=latest
  tags:
    - pip
    - python

- name: pip install ipython
  pip: name=ipython state=latest
  tags:
    - pip
    - python


