---
# from https://github.com/jnv/ansible-fedora-infra  ( fedora infrastructure )

- name: Add /etc/sudoers.d/sysadmin-main file
  action: copy src="private/files/sudo/sysadmin-main" dest=/etc/sudoers.d/ owner=root group=root mode=0600
  tags:
  - config

- name: Add /etc/sudoers.d/sudoers.d/ files
  action: copy src={{ item }} dest=/etc/sudoers.d/ owner=root group=root mode=0600
  with_fileglob:
    - "{{ sudoers_path }}/*"
  tags:
  - config